default:
  image: python:3.12

.autotag_base:
  allow_failure: true
  script:
    - ./auto-tag.sh
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH == $RELEASE_BRANCH

tag_and_merge->master:
  extends: .autotag_base
  variables:
    RELEASE_BRANCH: master
    TAG_ARGS: "--increment PATCH"
    AUTO_MERGE_BRANCH: staging

tag_and_merge->staging:
  extends: .autotag_base
  variables:
    RELEASE_BRANCH: staging
    TAG_ARGS: "--prerelease rc --increment PATCH"
    AUTO_MERGE_BRANCH: develop

tag->develop:
  extends: .autotag_base
  variables:
    RELEASE_BRANCH: develop
    TAG_ARGS: "--prerelease beta --increment PATCH"
