default:
  image: python:3.12

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: echo "Building!"
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH =~ /master|staging|develop/
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

test:
  stage: test
  script: echo "Testing!"
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH =~ /master|staging|develop/
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

.deploy_base:
  stage: deploy
  script:
   - echo "Deploying $TARGET_BRANCH!"
   - pip install nox
   - nox -s ci_autotag
  # releases must be performed serially, in order
  resource_group: "$TARGET_BRANCH"
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH == $TARGET_BRANCH

deploy-master:
  extends: .deploy_base
  variables:
    TARGET_BRANCH: master

deploy-staging:
  extends: .deploy_base
  variables:
    TARGET_BRANCH: staging

deploy-develop:
  extends: .deploy_base
  variables:
    TARGET_BRANCH: develop

.automerge_base:
  # always runs last
  stage: .post
  # it's ok if auto-merge does not succeed
  allow_failure: true
  script:
   - pip install nox
   - nox -s ci_automerge
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH == $TARGET_BRANCH

merge-master-to-staging:
  extends: .automerge_base
  variables:
    TARGET_BRANCH: master

merge-staging-to-develop:
  extends: .automerge_base
  variables:
    TARGET_BRANCH: staging

make-release:
  stage: deploy
  script:
   - pip install nox
   - nox -s ci_release
  rules:
    # add option to manually run release on staging pipelines: will convert the latest version on staging to a release
    - if: $CI_COMMIT_BRANCH == "staging" && $CI_PIPELINE_SOURCE != "schedule" && $CI_PIPELINE_SOURCE == "push"
      when: manual
      # allow_failure: true is required to prevent this job from blocking the pipeline.
      # Feature request: https://gitlab.com/gitlab-org/gitlab/-/issues/28036
      allow_failure: true
    - if: $CI_PIPELINE_SOURCE == "schedule" && $SCHEDULED_JOB_NAME == "make-release"
      when: manual
