default:
  image: python:3.11

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# https://pip.pypa.io/en/stable/topics/caching/
cache:
  paths:
    - .cache/pip

before_script:
  - |
    python --version ; pip --version  # For debugging
    pip install -r requirements.txt
    git log --graph --abbrev-commit --oneline --all --decorate

stages:
  - build
  - test
  - tide

# --- standard tide configuration below here ---

.common_rules:
  # provided for convenience: not used by tide
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" || $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_REF_PROTECTED == "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

.tide-base:
  stage: tide
  before_script:
    - env
    - pip install -e .

auto-tag:
  extends: .tide-base
  script: tide autotag --annotation "$TIDE_AUTOTAG_ANNOTATION"
  # must be performed serially, in order.
  resource_group: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_BRANCH
  variables:
    TIDE_AUTOTAG_ANNOTATION: $CI_COMMIT_TITLE
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" || $CI_COMMIT_TAG
      when: never
    # tide init ensures that our gitflow branches are protected
    - if: $CI_COMMIT_REF_PROTECTED == "true"

hotfix:
  extends: .tide-base
  # always runs last
  stage: .post
  # it's ok if hotfix does not succeed
  allow_failure: true
  script: tide hotfix
  # must be performed serially, in order.
  resource_group: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_BRANCH
  rules:
    # tide init ensures that $CI_DEFAULT_BRANCH is set to the most experimental branch
    - if: $CI_PIPELINE_SOURCE == "schedule" || $CI_COMMIT_TAG || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $TIDE_SKIP_HOTFIX == "true"
      when: never
    # tide init ensures that our gitflow branches are protected
    - if: $CI_COMMIT_REF_PROTECTED == "true"

promote:
  extends: .tide-base
  resource_group: promote
  script: tide promote
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $SCHEDULED_JOB_NAME == "promote"

# --- end standard tide configuration  --

# debug:
#   stage: build
#   script: env

# build:
#   extends:
#     - .common_rules
#   stage: build
#   script: echo "Building!"

unit-tests:
  extends:
    - .common_rules
  stage: test
  script: echo "Testing!"
#   script: nox -s unit_tests

smoke-tests:
  extends:
    - .common_rules
  stage: test
  script: echo "Testing!"
#   script: nox -s smoke_tests
